version: '3.8'

services:
  sadalu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sadalu
    ports:
      - "8010:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - sadalu-mysql

  sadalu-mysql:
    image: mariadb:10.10.2
    container_name: sadalu-mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
    driver: local
